### ISSUE TITLE
embeds

### ISSUE THREAD

**Issue by wascertified** [soswav/bigrat#16]
@bot.command(aliases=["suggestcmd"], description="Suggest a command for the bot")
async def suggestcommand(ctx, *, suggestion):
    suggestion_channel = bot.get_channel(1196024059939524608)
    embed = discord.Embed(title="new command suggestion!", description=suggestion, color=discord.Color.blurple())
    embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
    await suggestion_channel.send(embed=embed)@bot.command(aliases=["suggestcmd"], description="Suggest a command for the bot")
async def suggestcommand(ctx, *, suggestion):
    suggestion_channel = bot.get_channel(1196024059939524608)
    embed = discord.Embed(title="new command suggestion!", description=suggestion, color=discord.Color.blurple())
    embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
    await suggestion_channel.send(embed=embed)@bot.command(aliases=["suggestcmd"], description="Suggest a command for the bot")
async def suggestcommand(ctx, *, suggestion):
    suggestion_channel = bot.get_channel(1196024059939524608)
    embed = discord.Embed(title="new command suggestion!", description=suggestion, color=discord.Color.blurple())
    embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
    await suggestion_channel.send(embed=embed)@bot.command(aliases=["suggestcmd"], description="Suggest a command for the bot")
async def suggestcommand(ctx, *, suggestion):
    suggestion_channel = bot.get_channel(1196024059939524608)
    embed = discord.Embed(title="new command suggestion!", description=suggestion, color=discord.Color.blurple())
    embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
    await suggestion_channel.send(embed=embed)

**Comment by soswav** [comment]
Rejected

**Comment by soswav** [comment]
:-1:
